### ISSUE TITLE
Marking classlibs as dynamically loadable should be done via EnableDynamicLoading

### ISSUE THREAD

**Issue by vitek-karas** [Reloaded-Project/Reloaded.Core.Bootstrap#1]
In the readme for this project there's a section about troubleshooting - specifically the case of a classlib which doesn't have `.runtimeconfig.json` by default. Starting with recent .NET Core 3.0 previews (8 for sure, probably earlier) the right way to mark a classlib as a component which will be dynamically loaded is to add `<EnableDynamicLoading>true</EnableDynamicLoading>` to the project.

Under the hood it does currently set the `GenerateRuntimeConfigurationFiles` but this may change in the future.

**Comment by Sewer56** [comment]
Should be good as of 31991355fb68770d5536274949fe088d5bbeea54 and 1e6c73c4228c4039493b6cef678914288a16f8cb .
